## Question 1

In [1]:
import numpy as np
list_ = ['1','2', '3' , '4' , '5' ]
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


The type of the evariable list_ is a list and the variable array_list is a numpy n dimensional array.

## Question 2

In [2]:
print("elements of the list")
for elem in list_:
    print(type(elem))
    
print("\nelements of array_list")
for elem in array_list:
    print(type(elem))

elements of the list
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

elements of array_list
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Question 3

In [3]:
array_list = np.array(object = list_, dtype = int)
print("elements of the list")
for elem in list_:
    print(type(elem))
    
print("\nelements of array_list")
for elem in array_list:
    print(type(elem))

elements of the list
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

elements of array_list
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


The data types change to int32 from str_. As we explicitly specify the data type of the elements.

## Question 4

In [4]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print("shape of array",num_array.shape)
print("Size of the array",num_array.size)

shape of array (2, 3)
Size of the array 6


## Question 5

In [5]:
import numpy as np
zero_matrix=np.zeros((3,3))
print(zero_matrix)
print('\n',zero_matrix.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 (3, 3)


## Question 6

In [6]:
import numpy as np
identity=np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
